# Generated by Django 4.1.1 on 2022-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='account/<function user_directory_path at 0x0000016A0F2EBD00>/'),
        ),
    ]
