# Generated by Django 4.1.1 on 2022-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='account/<function user_directory_path at 0x000002186204BD00>/'),
        ),
    ]
