# Generated by Django 4.1.1 on 2022-10-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('EDITTING', 'Edditing'), ('CALCULATION', 'Calculation'), ('ASSIGNMENT', 'Assignment')], max_length=100)),
                ('academic_level', models.CharField(choices=[('HIGH SCHOOL', 'High School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University')], max_length=100)),
                ('subject_area', models.CharField(blank=True, choices=[('ESSAY', 'ESSAY'), ('ARTICLE', 'ARTICLE'), ('ASSIGNMENT', 'ASSIGNMENT'), ('CONTENT WRITING', 'CONTENT WRITING'), ('ADMISSION ESSAY', 'ADMISSION ESSAY'), ('ANNOTATED BIBLIOGRAPHY', 'ANNOTATED BIBLIOGRAPHY'), ('ARGUMENTATIVE ESSAY', 'ARGUMENTATIVE ESSAY'), ('ARTICLE REVIEW', 'ARTICLE REVIEW'), ('BOOK/MOVIE REVIEW', 'BOOK/MOVIE REVIEW'), ('BUSINESS PLAN', 'BUSINESS PLAN'), ('CAPSTONE PROJECT', 'CAPSTONE PROJECT'), ('CASE STUDY', 'CASE STUDY'), ('COURSEWORK', 'COURSEWORK'), ('CREATIVE WRITING', 'CREATIVE WRITING'), ('CRITICAL THINKING', 'CRITICAL THINKING'), ('DISSERTATION', 'DISSERTATION'), ('DISSERTATION CHAPTER', 'DISSERTATION CHAPTER'), ('LAB REPORT', 'LAB REPORT'), ('RESEARCH PAPER', 'RESEARCH PAPER'), ('RESEARCH PROPOSAL', 'RESEARCH PROPOSAL'), ('RESEARCH SUMMARY', 'RESEARCH SUMMARY'), ('SCHOLARSHIP ESSAY', 'SCHOLARSHIP ESSAY'), ('SPEECH', 'SPEECH'), ('STATISTIC PROJECT', 'STATISTIC PROJECT'), ('TERM PAPER', 'TERM PAPER'), ('THESIS/THESIS CHAPTER', 'THESIS/THESIS CHAPTER'), ('OTHER', 'OTHER'), ('PRESENTATION OR SPEECH', 'PRESENTATION OR SPEECH'), ('Q & A', 'Q & A'), ('SPEECH WORK', 'SPEECH WORK'), ('APPLICATION PAPER', 'APPLICATION PAPER'), ('ANALYSIS', 'ANALYSIS'), ('MEMO/LETTER', 'MEMO/LETTER'), ('OUTLINE', 'OUTLINE'), ('PERSONAL REFLECTION', 'PERSONAL REFLECTION'), ('REPORT', 'REPORT'), ('RESPONSE ESSAY', 'RESPONSE ESSAY'), ('ACCEPTANCE LETTER', 'ACCEPTANCE LETTER'), ('REVISION PAPER', 'REVISION PAPER'), ('BLOG WRITING', 'BLOG WRITING'), ('EXECUTIVE SUMMARY', 'EXECUTIVE SUMMARY'), ('EXTENDED REVISION', 'EXTENDED REVISION'), ('MICROSOFT PROJECT', 'MICROSOFT PROJECT'), ('PROGRESSIVE PAPER', 'PROGRESSIVE PAPER'), ('DISSERTATION EDITING', 'DISSERTATION EDITING'), ('GRANT PROPOSAL', 'GRANT PROPOSAL'), ('PARAPHRASE', 'PARAPHRASE'), ('NURSING CALCULATIONS', 'NURSING CALCULATIONS'), ('COMBINED SECTIONS', 'COMBINED SECTIONS'), ('DISSERTATION EDITING', 'DISSERTATION EDITING'), ('PROOFREADING/EDITING', 'PROOFREADING/EDITING'), ('BROCHURE', 'BROCHURE'), ('PAPER EDITING', 'PAPER EDITING')], max_length=100)),
                ('pages', models.PositiveIntegerField(blank=True, default=1)),
                ('words', models.PositiveIntegerField(blank=True, default=275)),
                ('prices', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deadline', models.DateField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
            options={
                'verbose_name': 'order type',
                'verbose_name_plural': 'Paper Types',
                'get_latest_by': 'order_date',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('paper_details', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='orders/files/')),
                ('subject_area', models.CharField(max_length=100)),
                ('writer_type', models.CharField(default='BW', max_length=2)),
                ('sources', models.PositiveIntegerField(default=0)),
                ('powerpoint_slides', models.PositiveIntegerField(default=0)),
                ('charts_graphs', models.PositiveIntegerField(default=0)),
                ('paper_format', models.CharField(default='MLA', max_length=5)),
                ('plag_report', models.CharField(default='standard', max_length=10)),
                ('extras', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreorder.ordertype')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
