# Generated by Django 4.1.1 on 2022-09-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('academic_level', models.CharField(max_length=100)),
                ('paper_type', models.CharField(blank=True, max_length=100)),
                ('subject_area', models.CharField(blank=True, max_length=100)),
                ('pages', models.PositiveIntegerField(blank=True, default=1)),
                ('words', models.PositiveIntegerField(blank=True, default=275)),
                ('prices', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deadline', models.DateField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
            options={
                'verbose_name': 'order type',
                'verbose_name_plural': 'Paper Types',
                'ordering': ['pages', 'order_date'],
                'get_latest_by': 'order_date',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('paper_details', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='orders/files/')),
                ('subject_area', models.CharField(max_length=100)),
                ('writer_type', models.CharField(default='BW', max_length=2)),
                ('sources', models.PositiveIntegerField(default=0)),
                ('powerpoint_slides', models.PositiveIntegerField(default=0)),
                ('charts_graphs', models.PositiveIntegerField(default=0)),
                ('paper_format', models.CharField(default='MLA', max_length=5)),
                ('plag_report', models.CharField(default='standard', max_length=10)),
                ('extras', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreorder.ordertype')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
