# Generated by Django 4.1.1 on 2022-09-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': 'order type (paper)', 'verbose_name_plural': 'Order (Paper) Types'},
        ),
    ]
