# Generated by Django 4.1.1 on 2022-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0002_remove_orderitem_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='grammerly_report',
            field=models.CharField(choices=[('None', 'None'), ('INCLUDE', 'Inlude')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='info_graph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='outline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='page_abstract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='page_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='progress_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sources_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='paper_format',
            field=models.CharField(choices=[('MLA', 'MLA'), ('APA', 'APA'), ('CHICAGO', 'Chicago'), ('HARVAD', 'Harvad'), ('OTHER', 'Other')], default='MLA', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plag_report',
            field=models.CharField(choices=[('None', None), ('STARNDARD', 'Standard'), ('PREMIUM', 'Premium')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='writer_type',
            field=models.CharField(choices=[('BW', 'Basic Writer'), ('FW', 'Fast Writer'), ('PW', 'Pro Writer')], default='BW', max_length=10),
        ),
    ]
