# Generated by Django 4.1.1 on 2022-09-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0002_alter_ordertype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='academic_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='paper_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='subject_area',
            field=models.CharField(max_length=100),
        ),
    ]
