# Generated by Django 4.1.1 on 2022-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0003_alter_ordertype_academic_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='subject_area',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
