# Generated by Django 4.1.1 on 2022-11-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0003_orderitem_grammerly_report_orderitem_info_graph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='info_graph',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='outline',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='page_abstract',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='page_summary',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='progress_update',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sources_copy',
        ),
    ]
