# Generated by Django 4.1.1 on 2022-09-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0005_alter_ordertype_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
